### ISSUE TITLE
alpine latest not working

### ISSUE THREAD

**Issue by bruzos** [SHyx0rmZ/capistrano-resource#2]
Hi I tried the latest version of the resource to do a capistrano deployment for a sinatra appa, and now it failing with a Error: 'Missing lib'

it works fixing the alpine to:
-FROM alpine:latests
to 
+FROM alpine:3.6

**Comment by SHyx0rmZ** [comment]
Sorry, I completely missed the notification for the issue. Having a look at it now.

**Comment by SHyx0rmZ** [comment]
Could you maybe retry with the new Docker image? So far I can't seem to reproduce the issue after updating the image.

**Comment by bruzos** [comment]
Here is the error log.
================================================
bundler: failed to load command: cap (/usr/bin/cap)
LoadError: cannot load such file -- etc
  /usr/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:6:in `require'
  /usr/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:6:in `<top (required)>'
  /usr/lib/ruby/gems/2.5.0/gems/sshkit-1.16.0/lib/sshkit/backends/netssh.rb:4:in `require'
  /usr/lib/ruby/gems/2.5.0/gems/sshkit-1.16.0/lib/sshkit/backends/netssh.rb:4:in `<top (required)>'
  /usr/lib/ruby/gems/2.5.0/gems/sshkit-1.16.0/lib/sshkit/all.rb:37:in `require_relative'
  /usr/lib/ruby/gems/2.5.0/gems/sshkit-1.16.0/lib/sshkit/all.rb:37:in `<top (required)>'
  /usr/lib/ruby/gems/2.5.0/gems/sshkit-1.16.0/lib/sshkit.rb:26:in `require_relative'
  /usr/lib/ruby/gems/2.5.0/gems/sshkit-1.16.0/lib/sshkit.rb:26:in `<top (required)>'
  /usr/lib/ruby/gems/2.5.0/gems/capistrano-3.10.1/lib/capistrano/all.rb:2:in `require'
  /usr/lib/ruby/gems/2.5.0/gems/capistrano-3.10.1/lib/capistrano/all.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.5.0/gems/capistrano-3.10.1/bin/cap:2:in `require'
  /usr/lib/ruby/gems/2.5.0/gems/capistrano-3.10.1/bin/cap:2:in `<top (required)>'
  /usr/bin/cap:23:in `load'
  /usr/bin/cap:23:in `<top (required)>'

**Comment by SHyx0rmZ** [comment]
The Docker image now also installs `ruby-etc`, which contains the missing files. The latest image should resolve your problem.
